services: mongodb

language: ruby

matrix:
  include:
    - rvm: 2.5.1
      gemfile: gemfiles/mongoid_head.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/mongoid_7.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/mongoid_6.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/mongoid_6.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/mongoid_6.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/mongoid_5.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/mongoid_4.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/mongoid_3.gemfile
    - rvm: 2.3.0
      before_script:
        - bundle exec danger
  allow_failures:
    - rvm: 2.5.1
      gemfile: gemfiles/mongoid_head.gemfile

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server

before_install:
  - gem update --system
  - gem update bundler
